---
- name: Install Vault
  hosts: localhost

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true

    - name: Create Vault User
      ansible.builtin.user:
        name: vault
        shell: /bin/bash
        home: /home/vault
      become: true
      register: uservault

    - name: Enable linger for vault user
      ansible.builtin.shell: |
        loginctl enable-linger "{{ uservault['uid'] }}"
      become: true

    - name: Pull vault image
      containers.podman.podman_image:
        name: docker.io/library/vault:1.13.3
      become_user: vault
      become: true

    - name: Create directories for vault
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        mode: '0776'
      loop:
        - /home/vault/vault/logs
        - /home/vault/vault/file
        - /home/vault/vault/config
      become_user: vault
      become: true

    - name: Copy Vault Config
      ansible.builtin.template:
        src: files/vault.local.json.j2
        dest: $HOME/vault/config/local.json
        mode: '0644'
      become_user: vault
      become: true

    - name: Run vault container
      ansible.builtin.shell: |
        podman run -d --cap-add=IPC_LOCK -v $HOME/vault/logs:/vault/logs:z -v $HOME/vault/config:/vault/config:z -v $HOME/vault/file:/vault/file:z  -e 'SKIP_CHOWN=true' -e 'SKIP_SETCAP=true' -p 8200:8200 docker.io/library/vault:1.13.3 server
      become_user: vault
      become: true

    # - name: Run vault container
    #   containers.podman.podman_container:
    #     name: vault
    #     image: docker.io/library/vault:1.13.3
    #     volume:
    #       - 'vault/logs:/vault/logs'
    #       - 'vault/config:/vault/config:z'
    #       - 'vault/file:/vault/file'
    #     ports:
    #       - "8200:8200"
    #     env:
    #       SKIP_CHOWN: true
    #       SKIP_SETCAP: true
    #     command: server
    #   become_user: vault
    #   become: true
