---
- name: Install Vault
  hosts: localhost

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true

    - name: Create Vault User
      ansible.builtin.user:
        name: vault
        shell: /bin/bash
        home: /home/vault
      become: true
      register: uservault

    - name: Enable linger for vault user
      ansible.builtin.shell: |
        loginctl enable-linger "{{ uservault['uid'] }}"
      become: true

    - name: Pull vault image
      containers.podman.podman_image:
        name: docker.io/library/vault:1.13.3
      become_user: vault
      become: true

    - name: Create directories for vault
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/vault/vault/logs
        - /home/vault/vault/file
        - /home/vault/vault/config
      become_user: vault
      become: true

    - name: Copy Vault Config
      ansible.builtin.template:
        src: files/vault.local.json.j2
        dest: $HOME/vault/config/local.json
      become_user: vault
      become: true
