---
- name: Install Docker
  hosts: localhost
  become: true

  tasks:
    - name: Install prerequisits
      ansible.builtin.package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add docker repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install docker-ce
      ansible.builtin.package:
        name: docker-ce
        state: present

    - name: Enable docker daemon
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add the user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
