---
- name: Install Vault
  hosts: localhost

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true

    - name: Create Vault User
      ansible.builtin.user:
        name: vault
        shell: /bin/bash
        home: /home/vault
      become: true

    - name: Pull vault image
      containers.podman.podman_image:
        name: docker.io/library/vault:1.13.3

    - name: Create directories for vault
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/vault/vault/logs
        - /home/vault/vault/file
        - /home/vault/vault/config
