---
- name: Install Docker
  hosts: localhost
  become: true

  tasks:
    - name: Install prerequisits
      ansible.builtin.package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: absent
