---
- name: Install Docker
  hosts: localhost
  become: true

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present

    - name: Create Vault User
      ansible.builtin.user:
        name: vault
        shell: /bin/bash
        home: /home/vault

    - name: Pull an vault image
      containers.podman.podman_image:
        name: docker.io/library/vault:1.13.3
