---
- name: Install Vault
  hosts: localhost

  tasks:
    - name: Read Vault
      community.hashi_vault.vault_read:
        url: http://ansible:8200
        path: secret/data/azure
        auth_method: userpass
        username: jesbe
        password: P@ssw0rd
      register: azure

    - name: Write output
      ansible.builtin.debug:
        msg: "{{ azure['data']['data']['data'] }}"
