---
- name: Write Vault
  hosts: localhost

  tasks:
    - name: Write Vault
      community.hashi_vault.vault_kv2_write:
        url: http://ansible:8200
        path: AWX
        auth_method: userpass
        username: write
        password: P@ssw0rd
        data:
          password: Passw0rd!
      register: key

    - name: Write output
      ansible.builtin.debug:
        msg: "{{ key }}"
