---
- name: Lookup Vault
  hosts: localhost
  vars:
    vuser: jesbe
    vpwd: P@ssw0rd

  tasks:

    - name: Lookup Vault
      ansible.builtin.set_fact:
        cred: "{{ lookup('community.hashi_vault.vault_kv2_get', 'AWX', url='http://ansible:8200', auth_method='userpass', username=vuser, password=vpwd) }}"

    - name: Show response
      ansible.builtin.debug:
        msg: "{{ cred.secret.password }}"

    - name: Create Namespace awx
      kubernetes.core.k8s:
        name: awx
        api_version: v1
        kind: Namespace
        state: present

    - name: Create Secret awx
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: awx-admin-password
            namespace: awx
          stringData:
            password: "{{ cred.secret.password }}"

    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        kind: Pod
      register: pod_list
