---
- name: Test
  hosts: localhost

  vars:
    user: jesbe
    rgname: "ansible-{{ user }}"
    vuser: jesbe
    vpwd: P@ssw0rd

  tasks:
    - name: Get Azure Creds
      ansible.builtin.include_tasks: azure_cred.yml

    - name: Get facts for all virtual networks
      azure.azcollection.azure_rm_virtualnetwork_info:
        resource_group: "{{ rgname }}"
      environment: "{{ azure_env }}"
      register: vnet

    - name: Show Vnet
      ansible.builtin.debug:
        msg: "{{ vnet }}"

    - name: Set Vnet facts
      ansible.builtin.set_fact:
        virtualnetwork: "{{ vnet['virtualnetworks'][0]['name'] }}"
        subnet: "{{ vnet['virtualnetworks'][0]['subnets'][0]['name'] }}"

    - name: Show Vnet
      ansible.builtin.debug:
        msg: "{{ virtualnetwork }} and {{ subnet }}"
