---
- name: Test
  hosts: localhost

  vars:
    user: jesbe
    rgname: "ansible-{{ user }}"
    vuser: jesbe
    vpwd: P@ssw0rd

  tasks:
    - name: Get Azure Creds
      ansible.builtin.include_tasks: azure_cred.yml

    - name: Test Set Local env
      ansible.builtin.debug:
        msg: "{{ azure_env }}"
