---
- name: Test
  hosts: localhost

  vars:
    user: jesbe
    rgname: "ansible_{{ user }}"

- include_playbook: 04_lookup_vault.yml
  tasks:
    - name: Get facts for all virtual networks
      azure.azcollection.azure_rm_virtualnetwork_info:
        resource_group: "{{ rgname }}"
