---
- name: Lookup Vault Kubernetes Creds
  ansible.builtin.set_fact:
    cred: "{{ lookup('community.hashi_vault.vault_kv2_get', 'kubernetes', url='http://ansible:8200', auth_method='userpass', username=vuser, password=vpwd) }}"

- name: Set Fact kubernetes Creds
  ansible.builtin.set_fact:
    kubernetes_env:
      K8S_AUTH_API_KEY: "{{ cred.secret.token }}"
      K8S_AUTH_HOST: "{{ cred.secret.host }}"
      K8S_AUTH_USERNAME: "{{ cred.secret.user }}"
